### ISSUE TITLE
Incompatibility with Haxe 4 preview 5

### ISSUE THREAD

**Issue by Dimous** [firefalcom/haxe-babylon#5]
Hello!
There is a breaking change in Haxe 4.0.0-preview.5 -- https://github.com/HaxeFoundation/haxe/issues/7413 that affects this extern -- https://github.com/HaxeFoundation/haxe/issues/7625#issuecomment-439703008 (the solution is in that comment).

**Comment by gogoprog** [comment]
Thanks for reporting, we will take care of it asap

**Comment by crazyjul** [comment]
I've pushed a new package, can you test?

**Comment by Dimous** [comment]
Almost there :)
Now I get another error:
> BABYLON.hx:15: characters 8-42 : Type not found : js.html.webgl.VertexArrayObjectOES

**Comment by Dimous** [comment]
VertexArrayObjectOES is deprecated and was removed in that commit -- https://github.com/HaxeFoundation/haxe/pull/7354/commits/18f742e81916d69f8ac8f290f00525199758927f

**Comment by Dimous** [comment]
`import #if (haxe_ver >= 4) js.html.webgl.VertexArrayObject #else js.html.webgl.VertexArrayObjectOES #end as WebGLVertexArrayObject; ` is doing the trick

**Comment by Dimous** [comment]
Awesome! Now its working!

**Comment by crazyjul** [comment]
Thanks for the report
